
# tap repositories and their packages

tap homebrew/core
brew aom
brew apr
brew apr-util
brew aspell
brew assimp
brew autoconf
brew automake
brew bash
brew bash-completion
brew bat
brew bdw-gc
brew bitwarden-cli
brew brotli
brew c-ares
brew ca-certificates
brew cairo
brew catimg
brew cfitsio
brew cgif
brew chezscheme
brew cmake
brew cmatrix
brew curl
brew dbus
brew docbook
brew docbook-xsl
brew double-conversion
brew duti
brew entr
brew exa
brew fd
brew fftw
brew figlet
brew fontconfig
brew freetype
brew fribidi
brew fzf
brew gawk
brew gcc
brew gd
brew gdbm
brew gdk-pixbuf
brew genact
brew gettext
brew ghostscript
brew giflib
brew git
brew git-crypt
brew git-delta
brew git-filter-repo
brew git-flow
brew git-lfs
brew git-subrepo
brew gitup
brew glances
brew glib
brew gmp
brew gnu-getopt
brew gnu-sed
brew gnupg
brew gnutls
brew go
brew gobject-introspection
brew goreleaser
brew gpatch
brew graphite2
brew graphviz
brew gts
brew guile
brew harfbuzz
brew hdf5
brew hping
brew htop
brew hunspell
brew hwloc
brew hyperfine
brew icu4c
brew imagemagick
brew imath
brew isl
brew ispell
brew jasper
brew jbig2dec
brew jd
brew jemalloc
brew jid
brew jpeg
brew jpeg-xl
brew jq
brew jrnl
brew lazygit
brew lf
brew lftp
brew libaec
brew libassuan
brew libavif
brew libb2
brew libde265
brew libev
brew libevent
brew libexif
brew libffi
brew libgcrypt
brew libgpg-error
brew libgsf
brew libheif
brew libice
brew libidn
brew libidn2
brew libimagequant
brew libksba
brew liblqr
brew libmatio
brew libmng
brew libmpc
brew libnghttp2
brew libomp
brew libpng
brew libpthread-stubs
brew libraw
brew librsvg
brew libsm
brew libspng
brew libssh2
brew libtasn1
brew libtermkey
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libuv
brew libvmaf
brew libx11
brew libxau
brew libxaw
brew libxcb
brew libxdmcp
brew libxext
brew libxft
brew libxinerama
brew libxml2
brew libxmu
brew libxpm
brew libxrender
brew libxt
brew libyaml
brew little-cms2
brew llvm
brew lua
brew lua-language-server
brew luajit-openresty
brew luarocks
brew luv
brew lz4
brew lzo
brew m4
brew mas
brew md4c
brew mingw-w64
brew mozjpeg
brew mpdecimal
brew mpfr
brew msgpack
brew ncurses
brew neofetch
brew neovim
brew netpbm
brew nettle
brew nghttp2
brew nmap
brew nnn
brew node
brew npth
brew nspr
brew nss
brew oniguruma
brew opam
brew open-mpi
brew openexr
brew openjdk
brew openjpeg
brew openldap
brew openslide
brew openssl@1.1
brew orc
brew p11-kit
brew pandoc
brew pango
brew pcre
brew pcre2
brew perltidy
brew pinentry
brew pixman
brew pkg-config
brew poppler
brew pyenv
brew pygments
brew pyright
brew python@3.10
brew python@3.8
brew python@3.9
brew qt
brew ragel
brew readline
brew reattach-to-user-namespace
brew remind
brew rename
brew ripgrep
brew rlwrap
brew rtmpdump
brew ruby
brew rust-analyzer
brew scons
brew screenresolution
brew shared-mime-info
brew shfmt
brew showkey
brew sqlite
brew stylua
brew subversion
brew swig
brew task
brew tasksh
brew taskwarrior-tui
brew tcl-tk
brew telnet
brew terraform
brew tig
brew timewarrior
brew tmux
brew tree-sitter
brew tty-clock
brew ucg
brew unbound
brew unibilium
brew universal-ctags --HEAD
brew utf8proc
brew valgrind --HEAD
brew vips
brew vlang
brew w3m
brew webp
brew wget
brew x265
brew xmlto
brew xorgproto
brew xterm
brew xz
brew yadm
brew yarn
brew zig
brew zlib
brew zstd

tap homebrew/cask-fonts
cask font-fontawesome
cask font-material-icons
cask font-roboto
cask font-roboto-mono
cask font-roboto-mono-nerd-font
cask font-ubuntu
cask font-victor-mono-nerd-font

tap homebrew/cask-versions
cask kitty-nightly

tap homebrew/services

tap homebrew/cask
cask alacritty
cask box-sync
cask db-browser-for-sqlite
cask docker
cask dotnet-sdk
cask firefox
cask google-chrome
cask iina
cask joplin
cask launchbar
cask qbittorrent
cask sf-symbols
cask swiftdefaultappsprefpane
cask xquartz

tap felixkratz/formulae
brew sketchybar

tap ggp1/tap
brew kure

tap goreleaser/tap

tap helix-editor/helix
brew helix

tap hors-org/hors
brew hors

tap jesseduffield/lazygit

tap koekeishiya/formulae
brew skhd
brew yabai --HEAD

tap louisbrunner/valgrind

tap ms-jpq/sad
brew sad

tap rcmdnk/file
brew brew-file

tap tinygo-org/tools

tap universal-ctags/universal-ctags

tap xwmx/taps
brew nb

# Other Cask applications
cask java

# App Store applications
appstore 1440147259  AdGuard for Safari        (1.11.4)
appstore 937984704   Amphetamine               (5.2.2)
appstore 1091189122  Bear                      (1.9.6)
appstore 1352778147  Bitwarden                 (1.33.0)
appstore 1477110326  Capital One Shopping      (1.0.19)
appstore 406056744   Evernote                  (10.37.3)
appstore 1480068668  Messenger                 (152.0)
appstore 1295203466  Microsoft Remote Desktop  (10.7.6)
appstore 992076693   MindNode                  (2.5.8)
appstore 1289197285  MindNode                  (2022.2.2)
appstore 1017470484  Next Meeting              (2.7)
appstore 425424353   The Unarchiver            (4.3.5)
appstore 1494210770  Tomato 2                  (2.3)
appstore 403388562   Transmit                  (4.4.13)
appstore 1278508951  Trello                    (2.13.1)
