tap "austinjones/taps"
tap "felixkratz/formulae"
tap "ggp1/tap"
tap "goreleaser/tap"
tap "helix-editor/helix"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "hors-org/hors"
tap "jesseduffield/lazygit"
tap "keith/formulae"
tap "koekeishiya/formulae"
tap "louisbrunner/valgrind"
tap "ms-jpq/sad"
tap "spicetify/tap"
tap "tinygo-org/tools"
tap "universal-ctags/universal-ctags"
tap "xwmx/taps"
brew "libpng"
brew "xz"
brew "aspell"
brew "bat"
brew "glib"
brew "cmake"
brew "cmatrix"
brew "curl"
brew "duti"
brew "entr"
brew "exa"
brew "fd"
brew "fzf"
brew "genact"
brew "ghcup"
brew "git-crypt"
brew "git-filter-repo"
brew "git-flow"
brew "git-lfs"
brew "git-subrepo"
brew "gitup"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "hadolint"
brew "harfbuzz"
brew "helix"
brew "hping"
brew "ncurses"
brew "htop"
brew "hyperfine"
brew "ispell"
brew "jid"
brew "jq"
brew "lf"
brew "lftp"
brew "lua-language-server"
brew "luarocks"
brew "mas"
brew "mingw-w64"
brew "neofetch"
brew "neovim"
brew "nmap"
brew "nnn"
brew "node"
brew "pandoc"
brew "pyright"
brew "rename"
brew "ripgrep"
brew "rlwrap"
brew "rust-analyzer"
brew "rustup-init"
brew "shfmt"
brew "showkey"
brew "spotify-tui"
brew "spotifyd", restart_service: true
brew "stylua"
brew "tasksh"
brew "taskwarrior-tui"
brew "telnet"
brew "terraform"
brew "terraform-ls"
brew "timewarrior"
brew "tmux"
brew "tty-clock"
brew "vifm"
brew "vlang"
brew "wget"
brew "yadm"
brew "yarn"
brew "goreleaser/tap/goreleaser"
brew "hors-org/hors/hors"
brew "jesseduffield/lazygit/lazygit"
brew "keith/formulae/reminders-cli"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai", args: ["HEAD"]
brew "ms-jpq/sad/sad"
brew "spicetify/tap/spicetify-cli"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "1password"
cask "1password-cli"
cask "adoptopenjdk8"
cask "alacritty"
cask "bartender"
cask "bunch"
cask "citrix-workspace"
cask "docker"
cask "dotnet-sdk"
cask "dropbox"
cask "firefox"
cask "font-fontawesome"
cask "font-material-icons"
cask "font-roboto-mono-nerd-font"
cask "google-chrome"
cask "google-chrome-beta"
cask "google-drive"
cask "iterm2"
cask "kitty-nightly"
cask "launchbar"
cask "launchcontrol"
cask "obsidian"
cask "omnigraffle"
cask "onyx"
cask "private-internet-access"
cask "qbittorrent"
cask "raycast"
cask "rectangle"
cask "sf-symbols"
cask "spaceman"
cask "spotify"
cask "steam"
cask "swiftdefaultappsprefpane"
cask "todoist"
cask "typora"
cask "visual-studio-code"
cask "vlc"
mas "1Password for Safari", id: 1569813296
mas "Amphetamine", id: 937984704
mas "Balance", id: 1637311725
mas "Capital One Shopping", id: 1477110326
mas "Developer", id: 640199958
mas "Eno From Capital One", id: 1590422864
mas "Evernote", id: 406056744
mas "Messenger", id: 1480068668
mas "Microsoft Remote Desktop", id: 1295203466
mas "MindNode", id: 992076693
mas "Silicio", id: 933627574
mas "The Unarchiver", id: 425424353
mas "Transmit", id: 403388562
mas "Trello", id: 1278508951
