tap "felixkratz/formulae"
tap "ggp1/tap"
tap "goreleaser/tap"
tap "helix-editor/helix"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "hors-org/hors"
tap "jesseduffield/lazygit"
tap "koekeishiya/formulae"
tap "louisbrunner/valgrind"
tap "ms-jpq/sad"
tap "tinygo-org/tools"
tap "universal-ctags/universal-ctags"
tap "xwmx/taps"
brew "libpng"
brew "aspell"
brew "bat"
brew "node"
brew "bitwarden-cli"
brew "readline"
brew "xz"
brew "python@3.9"
brew "glib"
brew "tcl-tk"
brew "catimg"
brew "chezscheme"
brew "cmake"
brew "cmatrix"
brew "curl"
brew "deno"
brew "python@3.10"
brew "duti"
brew "entr"
brew "exa"
brew "fd"
brew "gmp"
brew "fftw"
brew "figlet"
brew "fzf"
brew "gawk"
brew "genact"
brew "git-crypt"
brew "git-filter-repo"
brew "git-flow"
brew "git-lfs"
brew "git-subrepo"
brew "gitup"
brew "glances"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "harfbuzz"
brew "librsvg"
brew "graphviz"
brew "hping"
brew "ncurses"
brew "htop"
brew "hyperfine"
brew "libheif"
brew "imagemagick"
brew "ispell"
brew "jd"
brew "jid"
brew "jq"
brew "jrnl"
brew "lf"
brew "lftp"
brew "lua-language-server"
brew "luarocks"
brew "mas"
brew "mingw-w64"
brew "neofetch"
brew "neovim"
brew "nmap"
brew "nnn"
brew "opam"
brew "pandoc"
brew "perltidy"
brew "poppler"
brew "pyright"
brew "ragel"
brew "reattach-to-user-namespace"
brew "remind"
brew "rename"
brew "ripgrep"
brew "rlwrap"
brew "ruby"
brew "rust-analyzer"
brew "shfmt"
brew "showkey"
brew "stylua"
brew "subversion"
brew "tasksh"
brew "taskwarrior-tui"
brew "telnet"
brew "terraform"
brew "tig"
brew "timewarrior"
brew "tmux"
brew "tty-clock"
brew "ucg"
brew "vips"
brew "vlang"
brew "w3m"
brew "wget"
brew "yadm"
brew "yarn"
brew "zig"
brew "zlib"
brew "felixkratz/formulae/sketchybar"
brew "ggp1/tap/kure"
brew "goreleaser/tap/goreleaser"
brew "helix-editor/helix/helix"
brew "hors-org/hors/hors"
brew "jesseduffield/lazygit/lazygit"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai", args: ["HEAD"]
brew "louisbrunner/valgrind/valgrind", args: ["HEAD"], link: false
brew "ms-jpq/sad/sad"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
brew "xwmx/taps/nb"
cask "alacritty"
cask "box-sync"
cask "db-browser-for-sqlite"
cask "docker"
cask "dotnet-sdk"
cask "dropbox"
cask "firefox"
cask "font-fontawesome"
cask "font-material-icons"
cask "font-roboto"
cask "font-roboto-mono"
cask "font-roboto-mono-nerd-font"
cask "font-ubuntu"
cask "font-victor-mono-nerd-font"
cask "google-chrome"
cask "google-drive"
cask "iina"
cask "java"
cask "joplin"
cask "kitty-nightly"
cask "launchbar"
cask "qbittorrent"
cask "sf-symbols"
cask "swiftdefaultappsprefpane"
cask "xquartz"
mas "AdGuard for Safari", id: 1440147259
mas "Amphetamine", id: 937984704
mas "Bear", id: 1091189122
mas "Bitwarden", id: 1352778147
mas "Capital One Shopping", id: 1477110326
mas "Evernote", id: 406056744
mas "Messenger", id: 1480068668
mas "Microsoft Remote Desktop", id: 1295203466
mas "MindNode", id: 1289197285
mas "MindNode", id: 992076693
mas "Next Meeting", id: 1017470484
mas "The Unarchiver", id: 425424353
mas "Tomato 2", id: 1494210770
mas "Transmit", id: 403388562
mas "Trello", id: 1278508951
