#!/bin/bash

os="$(uname)"

pause() {
	read -p "Press enter to continue "
}

if [[ "$os" == "Darwin" ]]; then
	# xcode dev tools
	echo Installing xcode CLI tools
	xcode-select --install
  pause()

	# homebrew
	echo Installing homebrew
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  pause()

	# Essentials
	echo Installing essentials
  brew tap Homebrew/bundle
	brew install git yadm gpg
  pause()

	echo Cloning dots
	yadm clone git@github.com:brightpuddle/dots.git
	yadm decrypt
  pause()

	echo Brewing...
	brew file install
  pause()
fi
