version: 2
root-markers:
  - .git/
tools:
  # Formatters
  format-black: &format-black
    format-command: "black --quiet -"
    format-stdin: true
  format-dockfmt: &format-dockfmt
    format-command: "dockfmt fmt ${INPUT}"
    format-stdin: false
  format-fixjson: &format-fixjson
    format-command: "fixjson"
    format-stdin: true
  format-golines: &format-golines
    format-command: "golines"
    format-stdin: true
  format-isort: &format-isort
    format-command: "isort --quiet -"
    format-stdin: true
  format-rustfmt: &format-rustfmt
    format-command: "rustfmt"
    format-stdin: true
  format-prettier: &format-prettier
    format-command: "prettierd ${INPUT}"
    format-stdin: true
  format-rescript: &format-rescript
    format-command: "rescript format -stdin -"
    format-stdin: true
  format-shfmt: &format-shfmt
    format-command: "shfmt -ci -s -bn -"
    format-stdin: true
  format-stylua: &format-stylua
    format-command: "stylua -"
    format-stdin: true
  format-terraform: &format-terraform
    format-command: "terraform fmt -"
    format-stdin: true
  format-trim_newlines: &format-trim_newlines
    format-command: awk 'NF{print s $0; s=""; next} {s=s ORS}'
    format-stdin: true
  format-trim_whitespace: &format-trim_whitespace
    format-command: awk '{ sub(/[ \t]+$/, ""); print }'
    format-stdin: true
  format-vfmt: &format-vfmt
    format-command: "v fmt -"
    format-stdin: true
  format-xmllint: &format-xmllint
    format-command: "xmllint --format -"
    format-stdin: true

  # Linters
  lint-eslint: &lint-eslint
    lint-command: "eslint_d -f unix --stdin --stdin-filename ${INPUT}"
    lint-ignore-exit-code: true
    lint-stdin: true
    root-markers:
      - package.json
  lint-flake8: &lint-flake8
    lint-command: "flake8 --stdin-display-name ${INPUT} -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"
  lint-hadolint: &lint-hadolint
    lint-command: "hadolint --no-color"
    lint-formats:
      - "%f:%l %.%# %t%.%#: %m"
  lint-revive: &lint-revive
    lint-command: "revive ./..."
    lint-ignore-exit-code: true
    lint-formats:
      - "%f:%l:%c: %m"
  lint-shellcheck: &lint-shellcheck
    lint-command: "shellcheck -f gcc -x"
    lint-source: "shellcheck"
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

# ansiblelint
# eslint_d
languages:
  css:
    - <<: *format-prettier
  dockerfile:
    - <<: *format-trim_newlines
    - <<: *format-trim_whitespace
    - <<: *lint-hadolint
  go:
    - <<: *format-golines
    - <<: *lint-revive
  javascript:
    - <<: *format-prettier
    - <<: *lint-eslint
  javascriptreact:
    - <<: *format-prettier
    - <<: *lint-eslint
  typescript:
    - <<: *format-prettier
    - <<: *lint-eslint
  typescriptreact:
    - <<: *format-prettier
    - <<: *lint-eslint
  json:
    - <<: *format-fixjson
  lua:
    - <<: *format-stylua
  markdown:
    - <<: *format-prettier
  python:
    - <<: *format-black
    - <<: *format-isort
    - <<: *lint-flake8
  rescript:
    - <<: *format-rescript
  rust:
    - <<: *format-rustfmt
  sh:
    - <<: *format-shfmt
    - <<: *lint-shellcheck
  tf:
    - <<: *format-terraform
  xml:
    - <<: *format-xmllint
  vlang:
    - <<: *format-vfmt
  yaml:
    - <<: *format-prettier
