#!/bin/bash

# Homebrew (covers most compilers)
brew update
brew upgrade

# Rust
rustup update
cargo install-update --all

# Node libs
npm-check -yug

# Python libs
pipx upgrade-all
pip list -o | cut -d ' ' -f 1 | xargs -I{} pip install -U {}

# Go dependencies
goup

# MacOS and app store
softwareupdate -i --all --agree-to-license

# V
v up
v update

# Neovim
# nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
# TS?

# OCaml libs
# opam update
# opam upgrade -all -y --fixup

# Ruby
# gem update

# PERL
# cpan update???
