#!/bin/bash

# Homebrew (covers most compilers)
brew update
brew upgrade

# Rust
rustup update
cargo install-update --all

# Node libs
npm-check -yug

# Python libs
pipx upgrade-all
pip-review -av
# pip list -o | cut -d ' ' -f 1 | xargs -I{} pip install -U {}

# Go dependencies
gup update
