# Author: RayGervais<raygervais@hotmail.ca>

"attributes" = "base09"
"comment" = "base03"
"constant" = "base09"
"constructor" = "base0D"
"escape" = "base0C"
"function" = "base0D"
"keyword" = "base0E"
"label" = "base0E"
"namespace" = "base0E"
"number" = "base09"
"operator" = "base05"
"property" = "base0B"
"special" = "base0D"
"strings"  = "base0B"
"type" = "base0A"
"ui.background" = { bg = "base00" }
"ui.cursor" = { fg = "base05", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "base0A", modifiers = ["underlined"] }
"ui.help" = { bg = "base01", fg = "base06" }
"ui.help" = { fg = "base04", bg = "base01" }
"ui.linenr" = {fg = "base02" }
"ui.liner.selected" = "base02"
"ui.menu" = {fg = "base04", bg= "base01"}
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.popup" = { bg = "base01" }
"ui.selection" = "base02"
"ui.statusline" = {fg = "base04", bg = "base01" }
"ui.text" = { fg = "base05" }
"ui.text.focus" = { fg = "base05" }
"ui.window" = { bg = "base00" }
"variable" = "base08"

"info" = "base03"
"hint" = "base03"
"debug" = "base03"
"diagnostic" = "base03"
"error" = "base0E"

[palette]
base00 = "#2b303b"
base01 = "#343d46"
base02 = "#4f5b66"
base03 = "#65737e"
base04 = "#a7adba"
base05 = "#c0c5ce"
base06 = "#dfe1e8"
base07 = "#eff1f5"
base08 = "#bf616a"
base09 = "#d08770"
base0A = "#ebcb8b"
base0B = "#a3be8c"
base0C = "#96b5b4"
base0D = "#8fa1b3"
base0E = "#b48ead"
base0F = "#ab7967"
