return {
  "stevearc/conform.nvim",
  opts = {
    formatters_by_ft = {
      -- markdown = {},
      -- python = { "isort", "ruff_fix", "ruff_format" },
      -- rust = {},
      -- toml = { "taplo" },
      -- xml = { "xmllint" },
      -- yaml = { "yamlfmt" },
      go = { "goimports", "gofumpt" },
      fish = {},
      gohtmltmpl = { "djlint", "rustywind" },
      javascript = { "biome", "rustywind" },
      javascriptreact = { "biome", "rustywind" },
      json = { "jq" },
      ocaml = { "ocamlformat" },
      sh = { "shfmt" },
      swift = { "swiftlint" },
      templ = { "templ", "rustywind" },
      typescript = { "biome", "rustywind" },
      typescriptreact = { "biome", "rustywind" },
    },
  },
}
