-- Declarative plugin mgmt
return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	dependencies = { "williamboman/mason.nvim" },
	cmd = { "MasonToolsInstallSync" },
	config = function()
		require("mason-tool-installer").setup({
			ensure_installed = {
				"ansible-language-server",
				"ansible-lint",
				"biome",
				"black",
				"djlint",
				"golines",
				"gopls",
				"hadolint",
				"hclfmt",
				"html-lsp",
				"isort",
				"jq",
				"json-lsp",
				"lua-language-server",
				"prettierd",
				"pyright",
				"ruff",
				"rust-analyzer",
				"rustywind",
				"shfmt",
				"swiftlint",
				"taplo",
				"templ",
				"terraform-ls",
				"typescript-language-server",
				"xmllint",
				"yaml-language-server",
				"yamlfmt",
			},
		})
	end,
}
