theme = "nord"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[keys.normal]
C-d = ":q"
C-p = "file_picker"
K = "hover"
N = "goto_next_buffer"
P = "goto_previous_buffer"

[keys.normal.C-o]
w = ":w"


[keys.insert]
j = { k = "normal_mode" }
C-d = ":q"

[keys.insert.C-o]
w = ":w"

[keys.select]
C-d = ":q"

[keys.select.C-o]
w = ":w"
